---
all:
  children:
    macos_hosts:
      hosts:
        showdropgo-unityserver-macmini:
          ansible_host: 100.98.252.10
          ansible_user: showdropgo
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          location: "HMO"

    cloud_vms:
      hosts:
        vultr:
          ansible_host: 100.110.89.127
          public_ip: 45.32.202.94
          ansible_user: root
          unity_relay_target_ip: 100.98.252.10
          unity_relay_ports:
            - 20101
