---
# SSH public keys deployed to managed hosts
admin_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJtJsRLcsecaKPrGi0QcIGVwkWanK1PzuJ0YJAdHxZe showdropgo-ansible"

# Tailscale auth key — pass via vault or command line
tailscale_auth_key: ""
