---
- name: Update ShowDropGo DNS records
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloudflare_dns_records:
      - record: unity
        type: A
        value: "45.32.202.94"
        proxied: false
    cloudflare_dns_records_absent:
      - record: unity
        type: A
        value: "155.138.253.242"

  roles:
    - role: cloudflare-dns
      tags: dns
